# Generated by Django 3.1.5 on 2021-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceName', models.CharField(max_length=50)),
            ],
        ),
    ]
