# Generated by Django 3.1.5 on 2021-01-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0002_class_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='npcClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NPC.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='npcRace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NPC.race', verbose_name='Race'),
        ),
    ]
