# Generated by Django 3.1.5 on 2021-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0003_auto_20210127_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hitDice',
            field=models.SmallIntegerField(null=True),
        ),
    ]
