# Generated by Django 3.1.5 on 2021-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0005_remove_class_hitdice'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hitDice',
            field=models.IntegerField(choices=[(6, 'D6'), (8, 'D8'), (10, 'D10'), (12, 'D12')], null=True),
        ),
    ]
