# Generated by Django 3.1.5 on 2021-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0007_auto_20210127_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='hitDice',
        ),
        migrations.AddField(
            model_name='class',
            name='hitDice',
            field=models.IntegerField(choices=[(6, 'D6'), (8, 'D8'), (10, 'D10'), (12, 'D12')], null=True),
        ),
        migrations.DeleteModel(
            name='HitDice',
        ),
    ]
