# Generated by Django 3.1.5 on 2021-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0008_auto_20210127_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
