# Generated by Django 3.1.5 on 2021-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0009_profiencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiencies',
        ),
    ]
