# Generated by Django 3.1.5 on 2021-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0010_auto_20210127_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='proficiencies',
            field=models.ManyToManyField(to='NPC.Proficiencies'),
        ),
    ]
