# Generated by Django 3.1.5 on 2021-01-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0011_class_proficiencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmourProficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armourName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='proficiencies',
            name='profName',
        ),
        migrations.AddField(
            model_name='proficiencies',
            name='profName',
            field=models.ManyToManyField(to='NPC.ArmourProficiencies'),
        ),
    ]
