# Generated by Django 3.1.5 on 2021-01-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0012_auto_20210127_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficiencies',
            old_name='profName',
            new_name='Armour',
        ),
    ]
