# Generated by Django 3.1.5 on 2021-01-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0014_auto_20210127_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proficiencietypes',
            name='Armour',
        ),
        migrations.RemoveField(
            model_name='proficiencietypes',
            name='Weapons',
        ),
        migrations.RemoveField(
            model_name='class',
            name='proficiencies',
        ),
        migrations.DeleteModel(
            name='Proficiencies',
        ),
        migrations.DeleteModel(
            name='ProficiencieTypes',
        ),
    ]
