# Generated by Django 3.1.5 on 2021-01-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0015_auto_20210127_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProficiencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NPC.proficiencytype')),
            ],
        ),
    ]
