# Generated by Django 3.1.5 on 2021-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0017_class_proficiencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='proficiencies',
            field=models.ManyToManyField(to='NPC.ProficiencyType'),
        ),
    ]
