# Generated by Django 3.1.5 on 2021-01-27 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0018_auto_20210127_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['className']},
        ),
        migrations.AlterModelOptions(
            name='proficiency',
            options={'ordering': ['profType']},
        ),
        migrations.AlterModelOptions(
            name='proficiencytype',
            options={'ordering': ['profType']},
        ),
        migrations.AddField(
            model_name='character',
            name='npcLevel',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
